const coupons = [
  {
    promo: "2x1 en Sushi a Domicilio",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage: "https://thumbs.dreamstime.com/b/suchi-31590133.jpgg",
    status: 1,
    expiration: "5 días",
    redemptionType: "Online",
    commerceId: "By Happy",
    favorites: 34,
    totalRedemptions: 20,
  },
  {
    promo: "30% descuento en limpieza facial",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://www.claratoro.es/wp-content/uploads/2021/08/higiene-facial-profunda-1024x576.jpg",
    status: 1,
    expiration: "20 días",
    redemptionType: "Presencial",
    commerceId: "By Happy",
    favorites: 12,
    totalRedemptions: 9,
  },
  {
    promo: "$10.000 de descuento en Calzado de Mujer",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWs8yW79uF9JdXjRFrW8CeAcANXuXZ-eDE-Bt5k-NGbs8ztq6N0bJf3jQIKtcx2qnzRRY&usqp=CAU",
    status: 3,
    expiration: "3 días",
    redemptionType: "Presencial",
    commerceId: "By Happy",
    favorites: 39,
    totalRedemptions: 29,
  },
  {
    promo: "15% menos en el primer perfume",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://falabella.scene7.com/is/image/Falabella/7076033_1?wid=800&hei=800&qlt=70",
    status: 1,
    expiration: "12 días",
    redemptionType: "Ambos",
    commerceId: "By Happy",
    favorites: 19,
    totalRedemptions: 18,
  },
  {
    promo: "Marzo 2x1 en todo linea cosmetica ",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://firebasestorage.googleapis.com/v0/b/chicupon-39928.appspot.com/o/featured-images%2F0018%20Qullantu%20imagen.jpg?alt=media&token=bf6117a6-717b-48e0-a981-3856d406b33a",
    status: 2,
    expiration: "2 días",
    redemptionType: "Online",
    commerceId: "By Happy",
    favorites: 39,
    totalRedemptions: 29,
  },
  {
    promo: "Limpieza a domicilio, visita gratis",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://www.pediresfacil.net/wp-content/uploads/2017/04/handy-servicios-de-limpieza-a-domicilio-1024x400.jpg",
    status: 4,
    expiration: "2 días",
    redemptionType: "Online",
    commerceId: "By Happy",
    favorites: 16,
    totalRedemptions: 15,
  },
  {
    promo: "Jueves 30% descuento en cena para dos ",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&w=300",
    status: 5,
    expiration: "0 días",
    redemptionType: "Presencial",
    commerceId: "By Happy",
    favorites: 120,
    totalRedemptions: 98,
  },
  {
    promo: "Aperitivo gratis ",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://images.pexels.com/photos/3009802/pexels-photo-3009802.jpeg?auto=compress&cs=tinysrgb&w=400&lazy=load",
    status: 5,
    expiration: "0 días",
    redemptionType: "Presencial",
    commerceId: "By Happy",
    favorites: 120,
    totalRedemptions: 98,
  },
  {
    promo: "2x1 en Sushi a Domicilio",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://cajondelmaipochile.cl/wp-content/uploads/2021/01/Imagen-1-Gastronomia-SPA-Cajon-del-Maipo.jpg",
    status: 1,
    expiration: "5 días",
    redemptionType: "Online",
    commerceId: "BY HAPPY",
    favorites: 34,
    totalRedemptions: 20,
  },
  {
    promo: "30% descuento en limpieza facial",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://integralservicesltda.com/wp-content/uploads/2021/09/WhatsApp-Image-2021-09-04-at-11.02.01-AM-3.jpeg",
    status: 1,
    expiration: "20 días",
    redemptionType: "Presencial",
    commerceId: "By Happy",
    favorites: 12,
    totalRedemptions: 9,
  },
  {
    promo: "$10.000 de descuento en Calzado de Mujer",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJktswJxw_yyP-hmukvkbDzL-zrax4-eI2z6jJV3qyJb2IeQHL1rL4L9hjSgamVL27hQs&usqp=CAU",
    status: 3,
    expiration: "3 días",
    redemptionType: "Presencial",
    commerceId: "By Happy",
    favorites: 39,
    totalRedemptions: 29,
  },
  {
    promo: "15% menos en el primer perfume",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://www.miguelperis.com/wp-content/uploads/2020/09/casual-hombre.jpg",
    status: 1,
    expiration: "12 días",
    redemptionType: "Ambos",
    commerceId: "By Happy",
    favorites: 19,
    totalRedemptions: 18,
  },
  {
    promo: "Marzo 2x1 en todo linea cosmetica ",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://www.cocinacaserayfacil.net/wp-content/uploads/2020/03/Recetas-faciles-de-cocinar-y-sobrevivir-en-casa-al-coronavirus_2.jpg",
    status: 2,
    expiration: "2 días",
    redemptionType: "Online",
    commerceId: "By Happy",
    favorites: 39,
    totalRedemptions: 29,
  },
  {
    promo: "Limpieza a domicilio, visita gratis",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://falabella.scene7.com/is/image/Falabella/881947629_1?wid=1500&hei=1500&qlt=70",
    status: 4,
    expiration: "2 días",
    redemptionType: "Online",
    commerceId: "By Happy",
    favorites: 16,
    totalRedemptions: 15,
  },
  {
    promo: "Jueves 30% descuento en cena para dos ",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://cdn.shopify.com/s/files/1/0463/3917/collections/Poleras_Sitio_2_1200x1200.jpg?v=1605797027",
    status: 5,
    expiration: "0 días",
    redemptionType: "Presencial",
    commerceId: "By Happy",
    favorites: 120,
    totalRedemptions: 98,
  },
  {
    promo: "Aperitivo gratis ",
    maxRedemptionsByUser: 1,
    maxRedemptionsByPromo: 2,
    featuredImage:
      "https://nattivos.com/wp-content/uploads/2019/08/meca1-e1566944670627.jpg",
    status: 5,
    expiration: "0 días",
    redemptionType: "Presencial",
    commerceId: "By Happy",
    favorites: 120,
    totalRedemptions: 98,
  },
];
export default coupons;
